// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.DataAccess;

namespace WebApplication.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20210330200355_TwoMigrationDeleteDublicatAtTableListServicesGuid")]
    partial class TwoMigrationDeleteDublicatAtTableListServicesGuid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.DataAccess.Events", b =>
                {
                    b.Property<Guid>("GuidEventsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionOfTheEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageEvents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlannedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GuidEventsId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WebApplication.DataAccess.ListServices", b =>
                {
                    b.Property<Guid>("GuidListSevicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GuidListSevicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ListServices");
                });

            modelBuilder.Entity("WebApplication.DataAccess.News", b =>
                {
                    b.Property<Guid>("GuidNewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataNew")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuidNewsId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("WebApplication.DataAccess.Services", b =>
                {
                    b.Property<Guid>("GuidServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuidServicesId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WebApplication.DataAccess.Users", b =>
                {
                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleMame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfEnterprise")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuidId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication.DataAccess.ListServices", b =>
                {
                    b.HasOne("WebApplication.DataAccess.Services", "Services")
                        .WithMany("ListServices")
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Services");
                });

            modelBuilder.Entity("WebApplication.DataAccess.Services", b =>
                {
                    b.Navigation("ListServices");
                });
#pragma warning restore 612, 618
        }
    }
}
